/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



using RosSharp.RosBridgeClient.MessageTypes.Std;
using RosSharp.RosBridgeClient.MessageTypes.Geometry;

namespace RosSharp.RosBridgeClient.MessageTypes.AsaRosCommander
{
    public class AsaRelPoseStamped : Message
    {
        public override string RosMessageName => "asa_ros_commander/AsaRelPoseStamped";

        public Header header { get; set; }
        public string anchor_id { get; set; }
        public Pose pose { get; set; }

        public AsaRelPoseStamped()
        {
            this.header = new Header();
            this.anchor_id = "";
            this.pose = new Pose();
        }

        public AsaRelPoseStamped(Header header, string anchor_id, Pose pose)
        {
            this.header = header;
            this.anchor_id = anchor_id;
            this.pose = pose;
        }
    }
}
