/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



using RosSharp.RosBridgeClient.MessageTypes.Geometry;

namespace RosSharp.RosBridgeClient.MessageTypes.AsaRos
{
    public class FoundAnchor : Message
    {
        public override string RosMessageName => "asa_ros_msgs/FoundAnchor";

        //  Azure Spatial Anchors ID (64-character UUID string) that was found.
        public string anchor_id { get; set; }
        //  The pose of the ASA anchor expressed in the world (odometry) coordinate frame.
        //  The "world" frame is defined as whatever the global/world frame that the
        //  camera poses are expressed in.
        public TransformStamped anchor_in_world_frame { get; set; }

        public FoundAnchor()
        {
            this.anchor_id = "";
            this.anchor_in_world_frame = new TransformStamped();
        }

        public FoundAnchor(string anchor_id, TransformStamped anchor_in_world_frame)
        {
            this.anchor_id = anchor_id;
            this.anchor_in_world_frame = anchor_in_world_frame;
        }
    }
}
