/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



using RosSharp.RosBridgeClient.MessageTypes.Std;

namespace RosSharp.RosBridgeClient.MessageTypes.Cgal
{
    public class TriangleMeshStamped : Message
    {
        public override string RosMessageName => "cgal_msgs/TriangleMeshStamped";

        public Header header { get; set; }
        public TriangleMesh mesh { get; set; }

        public TriangleMeshStamped()
        {
            this.header = new Header();
            this.mesh = new TriangleMesh();
        }

        public TriangleMeshStamped(Header header, TriangleMesh mesh)
        {
            this.header = header;
            this.mesh = mesh;
        }
    }
}
