/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



using RosSharp.RosBridgeClient.MessageTypes.Shape;
using RosSharp.RosBridgeClient.MessageTypes.Geometry;

namespace RosSharp.RosBridgeClient.MessageTypes.Cgal
{
    public class TriangleMesh : Message
    {
        public override string RosMessageName => "cgal_msgs/TriangleMesh";

        //  Triangle vertices index:
        public MeshTriangle[] triangles { get; set; }
        //  vertices:
        public Point[] vertices { get; set; }
        //  optional string ids for vertices and triangles
        //  if not set, ids are strings of the indizes
        public string[] triangle_ids { get; set; }
        public string[] vertex_ids { get; set; }

        public TriangleMesh()
        {
            this.triangles = new MeshTriangle[0];
            this.vertices = new Point[0];
            this.triangle_ids = new string[0];
            this.vertex_ids = new string[0];
        }

        public TriangleMesh(MeshTriangle[] triangles, Point[] vertices, string[] triangle_ids, string[] vertex_ids)
        {
            this.triangles = triangles;
            this.vertices = vertices;
            this.triangle_ids = triangle_ids;
            this.vertex_ids = vertex_ids;
        }
    }
}
